name: CI
on:
  pull_request:
    paths:
      - '**.yaml'
    branches:
      - master
  push:
    paths:
      - '**.yaml'
    branches:
      - master

jobs:
  lint:
    name: Lint YAML
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Install YAMLlint
      run: pip install yamllint 
    - name: Run the linter
      run: yamllint --strict -c ./.yamllint.yaml *.yaml **/*.yaml
  generate_and_test:
    name: Generate and test ZCL
    needs: lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        path: zyaml
    - uses: actions/checkout@v2
      with:
        repository: hemtjanst/zcl
        path: zcl
    - uses: actions/setup-go@v2
      with:
        go-version: '1.14'
    - name: Run zclgen
      working-directory: ./zcl
      run: |
        go run hemtjan.st/zcl/cmd/zclgen -definition-path ../zyaml
    - name: Build updated ZCL
      working-directory: ./zcl
      run: |
        go build hemtjan.st/zcl/...
    - name: Run ZCL tests
      working-directory: ./zcl
      run: |
        go test -v hemtjan.st/zcl/...
  update:
    name: Push updated ZCL
    if: github.ref == 'refs/heads/master'
    needs: generate_and_test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        path: zyaml
    - uses: actions/checkout@v2
      with:
        repository: hemtjanst/zcl
        path: zcl
        ssh-key: ${{ secrets.BOT_SSH_KEY }}
    - uses: actions/setup-go@v2
      with:
        go-version: '1.14'
    - name: Run zclgen
      working-directory: ./zcl
      run: |
        go run hemtjan.st/zcl/cmd/zclgen -definition-path ../zyaml
        go build hemtjan.st/zcl/...
        go mod tidy
    - name: Commit, push and PR
      working-directory: ./zcl
      env:
        GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
      run: |
        if test -n "$(git status -s)"; then
          git config user.name "Hemtjanst Bot"
          git config user.email "63548820+hemtjanst-bot@users.noreply.github.com"
          git checkout -b zyaml-${GITHUB_SHA}
          git add .
          git commit -m "Update to zyaml ${GITHUB_SHA}" -m "See https://github.com/hemtjanst/zyaml/commit/${GITHUB_SHA}"
          git push origin zyaml-${GITHUB_SHA}
          hub pull-request -m "Update ZCL to zyaml ${GITHUB_SHA}" --reviewer daenney,bonan
        else
          echo "No changes to generated code"
        fi
