name: Lint the YAML
on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Install YAMLlint
      run: pip install yamllint 
    - name: Run the linter
      run: yamllint -c ./.yamllint.yaml *.yaml **/*.yaml
